project_name: fail2ban_exporter

before:
  hooks:
    - go mod tidy

builds:
  - id: fail2ban_exporter
    binary: fail2ban_exporter
    env:
      - CGO_ENABLED=0
    goos: [linux]
    goarch: [amd64, arm64]

archives:
  - id: binary
    formats: [ binary ]

changelog:
  use: git

release:
  draft: false
  prerelease: auto
  # You can omit the repo info; GoReleaser infers from git remote.
  # github:
  #   owner: <your-gh-user-or-org>
  #   name: <your-repo-name>
